### ISSUE TITLE
标签数据和Range-angle数据不对齐

### ISSUE THREAD

**Issue by luckyyf0517** [Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection#11]
标签csv文件中的px、py转换到range-angle坐标系下，在距离稍远的地方出现较大的误差，其中ramap根据雷达参数计算，想请问是自动化标注产生的距离估计误差还是我计算过程出现了问题

**Comment by Xiangyu-Gao** [comment]
Can you show an example? thanks

**Comment by xhhxbg** [comment]
Thank you for your reply. Here is an example, i read a raw adc file from date sequence `2019_04_09_bms1000`, frame `000808.mat`, for instance. 

The annotation info is 
```
22,80,-1.11408487,11.31695161,0.6,1.7
```
We can get `px = -1.11 m` and `py = 11.31 m`, which are presented in Cartesian coordinate, so we can calculate the range and angle-of-arrival of the target by $r=\sqrt{x^2+y^2}$ and $a=\arctan{x/y}$ : `r=11.37 m, a=-5.62 deg`. 

Then I used the function `labelmap2ra` provided in RAMPCNN source code, to map the target into confmap. 

Here I draw the ra-view of the radar data, strictly using the mmwave radar parameters provided in https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/blob/main/config.py, and I draw the target point on the figure as well. (According to the radar config, the resolution of range-bin is about 0.22m. )

![image](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/108784091/a767403d-9a1f-4269-b368-89efc5c3e23a)

Obviously there is a disalignemnt between the ramap and the annotation. But in some other frames, when the target is close to the radar, the location of annotation looks correct, for example, frame `000220.mat`. 

![image](https://github.com/Xiangyu-Gao/Raw_ADC_radar_dataset_for_automotive_object_detection/assets/108784091/b814f27e-49b4-4517-8c1e-40c3c6775feb)

I am trying to use the dataset for a semantic segmentation task, but the problem do bother me a lot. 

I wonder if I understood the mapping px and py to the RA coordinate correctly, or is there any operation or setting that I missed, or it's simply due to estimation errors caused by semi-automated annotation. 

Thank you!

**Comment by xhhxbg** [comment]
I also considered the `crop` operation mentioned in https://github.com/Xiangyu-Gao/Radar-multiple-perspective-object-detection/blob/aff04b354f07f2689dfd8fcf6fcb68a9404eb73a/utils/mappings.py#L15, but the impact on resolution is small and the results are not improved.

**Comment by Xiangyu-Gao** [comment]
The crop operation should have little effect on that. I assume this mismatch is an error from the auto-labeling. The further the distance, the larger the error usually.
